name: update-target-repo
description: Update Target Repo with Compiled Resume
inputs:
  target-repo:
    required: true
  repo-resume-path:
    required: true
  commit-message:
    required: true

runs: 
  using: "composite"
  steps:
    - name: Clone target repository
      shell: bash
      run: |
        git clone ${{ inputs.target-repo }} portfolio

    - name: Copy generated resume to target repository path
      shell: bash
      run: |-
        chmod +xwr ${{ github.workspace }}/out/resume.pdf
        install -D ${{ github.workspace }}/out/resume.pdf portfolio/${{ inputs.repo-resume-path }}

    - name: Commit and push to target repository
      shell: bash
      run: |
        cd portfolio
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "${{ inputs.commit-message }}"
        git remote set-url origin ${{ inputs.target-repo }}
        git push
